export type Language = 'pl' | 'en' | 'de' | 'es' | 'fr' | 'ru' | 'ja';

export const translations: Record<Language, any> = {
  pl: {
    nav: { start: 'Start', portfolio: 'Portfolio' },
    hero: { badge: 'Montażysta Video', subtitle1: 'Twoja wizja', subtitle2: 'Moja produkcja', subtitle3: 'Rytm', subtitle4: 'Płynność', subtitle5: 'Historia', btnStart: 'Rozpocznij Projekt', btnPortfolio: 'Zobacz Portfolio', stat1: 'Opinii klientów', stat2: 'Zadowolonych twórców', stat3: 'Zmontowanych filmów', scroll: 'Przewiń' },
    carousel: { title: 'Zaufali mi' },
    portfolio: { label: 'Portfolio', title: 'Wybrane<br />Prace', subtitle: 'Najlepsze projekty z mojego portfolio – kreatywne rozwiązania dla twórców.', btnAll: 'Zobacz pełne portfolio →', filterAll: 'Wszystkie', filterVideos: 'Videos', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'Brak projektów w tej kategorii.', pageTitle: 'Wszystkie Projekty' },
    about: { title: 'O mnie', p1: 'Jestem Jacek. Od 6 lat zajmuję się montażem wideo zarówno dla mniejszych, jak i większych twórców internetowych.', p2: 'W swojej codziennej pracy korzystam głównie ze sprawdzonego pakietu Creative Cloud, opierając swoje produkcje na Premiere Pro oraz After Effects. Poza pasją do tworzenia treści wideo, interesuję się również programowaniem oraz sportem. Obecnie wciąż się rozwijam, łącząc zlecenia z nauką w szkole średniej.' },
    qa: { label: 'FAQ', title: 'Pytania i Odpowiedzi', subtitle: 'Popularne pytania dotyczące mojego procesu pracy, narzędzi i czasu realizacji.', q1: 'Jaki jest typowy czas realizacji?', a1: 'Standardowy czas realizacji to 3-5 dni roboczych. Ekspresowa realizacja dostępna na żądanie.', q2: 'Jakiego oprogramowania używasz?', a2: 'Adobe Premiere Pro, After Effects i DaVinci Resolve do korekcji kolorów.', q3: 'Jak przebiega proces współpracy?', a3: 'Zaczynamy od rozmowy konsultacyjnej, potem przesyłasz materiał. Regularne aktualizacje i rundy poprawek w pakiecie.', q4: 'Czy zapewniacie udźwiękowienie i muzykę?', a4: 'Tak, muzyka bez tantiem i udźwiękowienie są zawarte w każdym pakiecie.', q5: 'Jak działają poprawki?', a5: 'Nieograniczone poprawki aż będziesz w 100% zadowolony z wyniku.' },
    contact: { status: 'Dostępny', title1: 'Zacznijmy', title2: 'Montaż.', subtitle: 'Masz surowy materiał? Skopiuj adres e-mail i omówmy szczegóły!', btnCopy: 'Skopiuj E-mail', btnCopied: 'Skopiowano!' },
    footer: { home: 'Strona główna', portfolio: 'Portfolio', about: 'O mnie', faq: 'FAQ', tttTitle: 'Chcesz mnie pokonać? Spróbuj!', tttWin: 'Wygrałeś!', tttLose: 'Przegrałeś!', tttDraw: 'Remis!', tttPlayAgain: 'Zagraj ponownie' }
  },
  en: {
    nav: { start: 'Home', portfolio: 'Portfolio' },
    hero: { badge: 'Video Editor', subtitle1: 'Your vision', subtitle2: 'My production', subtitle3: 'Rhythm', subtitle4: 'Flow', subtitle5: 'Story', btnStart: 'Start Project', btnPortfolio: 'View Portfolio', stat1: 'Client Reviews', stat2: 'Satisfied Creators', stat3: 'Edited Videos', scroll: 'Scroll' },
    carousel: { title: 'Trusted by' },
    portfolio: { label: 'Portfolio', title: 'Selected<br />Works', subtitle: 'The best projects from my portfolio – creative solutions for creators.', btnAll: 'View full portfolio →', filterAll: 'All', filterVideos: 'Videos', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'No projects in this category.', pageTitle: 'All Projects' },
    about: { title: 'About me', p1: 'I am Jacek. For 6 years, I have been editing videos for both smaller and larger online creators.', p2: 'In my daily work, I mainly use the proven Creative Cloud suite, basing my productions on Premiere Pro and After Effects. Besides my passion for creating video content, I am also interested in programming and sports. I am currently continuing to develop while combining freelance work with high school.' },
    qa: { label: 'FAQ', title: 'Questions & Answers', subtitle: 'Popular questions about my workflow, tools, and delivery time.', q1: 'What is the typical delivery time?', a1: 'Standard delivery time is 3-5 business days. Express delivery is available upon request.', q2: 'What software do you use?', a2: 'Adobe Premiere Pro, After Effects, and DaVinci Resolve for color grading.', q3: 'How does the collaboration process work?', a3: 'We start with a consultation, then you send the footage. Regular updates and revision rounds are included.', q4: 'Do you provide sound design and music?', a4: 'Yes, royalty-free music and sound design are included in every package.', q5: 'How do revisions work?', a5: 'Unlimited revisions until you are 100% satisfied with the result.' },
    contact: { status: 'Available', title1: 'Let\'s start', title2: 'Editing.', subtitle: 'Got raw footage? Copy the email address and let\'s discuss the details!', btnCopy: 'Copy E-mail', btnCopied: 'Copied!' },
    footer: { home: 'Home', portfolio: 'Portfolio', about: 'About me', faq: 'FAQ', tttTitle: 'Want to beat me? Try it!', tttWin: 'You won!', tttLose: 'You lost!', tttDraw: 'Draw!', tttPlayAgain: 'Play again' }
  },
  de: {
    nav: { start: 'Start', portfolio: 'Portfolio' },
    hero: { badge: 'Video-Editor', subtitle1: 'Deine Vision', subtitle2: 'Meine Produktion', subtitle3: 'Rhythmus', subtitle4: 'Fluss', subtitle5: 'Geschichte', btnStart: 'Projekt starten', btnPortfolio: 'Portfolio ansehen', stat1: 'Kundenbewertungen', stat2: 'Zufriedene Creator', stat3: 'Bearbeitete Videos', scroll: 'Scrollen' },
    carousel: { title: 'Vertraut von' },
    portfolio: { label: 'Portfolio', title: 'Ausgewählte<br />Werke', subtitle: 'Die besten Projekte aus meinem Portfolio – kreative Lösungen für Creator.', btnAll: 'Gesamtes Portfolio ansehen →', filterAll: 'Alle', filterVideos: 'Videos', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'Keine Projekte in dieser Kategorie.', pageTitle: 'Alle Projekte' },
    about: { title: 'Über mich', p1: 'Ich bin Jacek. Seit 6 Jahren bearbeite ich Videos für kleinere und größere Online-Creator.', p2: 'In meiner täglichen Arbeit nutze ich hauptsächlich die bewährte Creative Cloud Suite und basiere meine Produktionen auf Premiere Pro und After Effects. Neben meiner Leidenschaft für die Erstellung von Videoinhalten interessiere ich mich auch für Programmierung und Sport. Derzeit entwickle ich mich weiter, indem ich meine freiberufliche Arbeit mit der High School verbinde.' },
    qa: { label: 'FAQ', title: 'Fragen & Antworten', subtitle: 'Beliebte Fragen zu meinem Workflow, Tools und Lieferzeit.', q1: 'Wie ist die typische Lieferzeit?', a1: 'Die Standardlieferzeit beträgt 3-5 Werktage. Express-Lieferung auf Anfrage möglich.', q2: 'Welche Software verwendest du?', a2: 'Adobe Premiere Pro, After Effects und DaVinci Resolve für die Farbkorrektur.', q3: 'Wie funktioniert der Zusammenarbeitsprozess?', a3: 'Wir beginnen mit einer Beratung, dann sendest du das Filmmaterial. Regelmäßige Updates und Überarbeitungsrunden sind inklusive.', q4: 'Stellst du Sounddesign und Musik zur Verfügung?', a4: 'Ja, lizenzfreie Musik und Sounddesign sind in jedem Paket enthalten.', q5: 'Wie funktionieren Überarbeitungen?', a5: 'Unbegrenzte Überarbeitungen, bis du zu 100% mit dem Ergebnis zufrieden bist.' },
    contact: { status: 'Verfügbar', title1: 'Lass uns', title2: 'Beginnen.', subtitle: 'Hast du Rohmaterial? Kopiere die E-Mail-Adresse und lass uns die Details besprechen!', btnCopy: 'E-Mail kopieren', btnCopied: 'Kopiert!' },
    footer: { home: 'Start', portfolio: 'Portfolio', about: 'Über mich', faq: 'FAQ', tttTitle: 'Willst du mich schlagen? Versuch es!', tttWin: 'Gewonnen!', tttLose: 'Verloren!', tttDraw: 'Unentschieden!', tttPlayAgain: 'Nochmal spielen' }
  },
  es: {
    nav: { start: 'Inicio', portfolio: 'Portafolio' },
    hero: { badge: 'Editor de Video', subtitle1: 'Tu visión', subtitle2: 'Mi producción', subtitle3: 'Ritmo', subtitle4: 'Fluidez', subtitle5: 'Historia', btnStart: 'Iniciar Proyecto', btnPortfolio: 'Ver Portafolio', stat1: 'Reseñas', stat2: 'Creadores satisfechos', stat3: 'Videos editados', scroll: 'Desplazar' },
    carousel: { title: 'Con la confianza de' },
    portfolio: { label: 'Portafolio', title: 'Obras<br />Seleccionadas', subtitle: 'Los mejores proyectos de mi portafolio – soluciones creativas.', btnAll: 'Ver portafolio completo →', filterAll: 'Todo', filterVideos: 'Videos', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'No hay proyectos en esta categoría.', pageTitle: 'Todos los Proyectos' },
    about: { title: 'Sobre mí', p1: 'Soy Jacek. Desde hace 6 años me dedico a la edición de video para creadores pequeños y grandes.', p2: 'En mi trabajo diario utilizo el ecosistema Adobe (Premiere Pro, After Effects). Aparte de mi pasión por el video, me interesa la programación y los deportes. Actualmente compagino mi trabajo con los estudios.' },
    qa: { label: 'FAQ', title: 'Preguntas y Respuestas', subtitle: 'Preguntas comunes sobre el proceso, herramientas y tiempos.', q1: '¿Cuál es el tiempo de entrega?', a1: 'Normalmente de 3 a 5 días hábiles.', q2: '¿Qué software utilizas?', a2: 'Premiere Pro, After Effects y DaVinci Resolve.', q3: '¿Cómo es el proceso?', a3: 'Consultoría inicial, envío de material, actualizaciones y revisiones.', q4: '¿Incluyes música y sonido?', a4: 'Sí, todo está incluido.', q5: '¿Y las revisiones?', a5: 'Revisiones ilimitadas hasta que estés 100% satisfecho.' },
    contact: { status: 'Disponible', title1: 'Empecemos la', title2: 'Edición.', subtitle: '¿Tienes material en bruto? ¡Copia el email y hablemos!', btnCopy: 'Copiar Email', btnCopied: '¡Copiado!' },
    footer: { home: 'Inicio', portfolio: 'Portafolio', about: 'Sobre mí', faq: 'FAQ', tttTitle: '¿Quieres ganarme? ¡Inténtalo!', tttWin: '¡Ganaste!', tttLose: '¡Perdiste!', tttDraw: '¡Empate!', tttPlayAgain: 'Jugar de nuevo' }
  },
  fr: {
    nav: { start: 'Accueil', portfolio: 'Portfolio' },
    hero: { badge: 'Monteur Vidéo', subtitle1: 'Votre vision', subtitle2: 'Ma production', subtitle3: 'Rythme', subtitle4: 'Fluidité', subtitle5: 'Histoire', btnStart: 'Lancer le Projet', btnPortfolio: 'Voir le Portfolio', stat1: 'Avis clients', stat2: 'Créateurs satisfaits', stat3: 'Vidéos montées', scroll: 'Défiler' },
    carousel: { title: 'Ils m\'ont fait confiance' },
    portfolio: { label: 'Portfolio', title: 'Travaux<br />Sélectionnés', subtitle: 'Les meilleurs projets de mon portfolio.', btnAll: 'Voir tout le portfolio →', filterAll: 'Tout', filterVideos: 'Vidéos', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'Aucun projet dans cette catégorie.', pageTitle: 'Tous les Projets' },
    about: { title: 'À propos', p1: 'Je suis Jacek. Depuis 6 ans, je monte des vidéos pour des créateurs de toutes tailles.', p2: 'J\'utilise la suite Adobe (Premiere Pro, After Effects). Passionné de vidéo, de programmation et de sport, je concilie mon travail et mes études.' },
    qa: { label: 'FAQ', title: 'Questions et Réponses', subtitle: 'Questions fréquentes sur mon processus de travail.', q1: 'Quel est le délai habituel ?', a1: '3 à 5 jours ouvrés.', q2: 'Quels logiciels utilisez-vous ?', a2: 'Premiere Pro, After Effects et DaVinci Resolve.', q3: 'Comment se passe la collaboration ?', a3: 'Consultation, envoi des fichiers, et révisions.', q4: 'La musique est-elle incluse ?', a4: 'Oui, la musique libre de droits est incluse.', q5: 'Et les modifications ?', a5: 'Modifications illimitées jusqu\'à 100% de satisfaction.' },
    contact: { status: 'Disponible', title1: 'Commençons le', title2: 'Montage.', subtitle: 'Vous avez des rushs ? Copiez l\'email et discutons-en !', btnCopy: 'Copier l\'Email', btnCopied: 'Copié !' },
    footer: { home: 'Accueil', portfolio: 'Portfolio', about: 'À propos', faq: 'FAQ', tttTitle: 'Envie de jouer ?', tttWin: 'Gagné !', tttLose: 'Perdu !', tttDraw: 'Égalité !', tttPlayAgain: 'Rejouer' }
  },
  ru: {
    nav: { start: 'Главная', portfolio: 'Портфолио' },
    hero: { badge: 'Видеомонтажер', subtitle1: 'Ваше видение', subtitle2: 'Мое производство', subtitle3: 'Ритм', subtitle4: 'Поток', subtitle5: 'История', btnStart: 'Начать Проект', btnPortfolio: 'Смотреть Портфолио', stat1: 'Отзывов', stat2: 'Довольных авторов', stat3: 'Смонтированных видео', scroll: 'Вниз' },
    carousel: { title: 'Мне доверяют' },
    portfolio: { label: 'Портфолио', title: 'Избранные<br />Работы', subtitle: 'Лучшие проекты из моего портфолио.', btnAll: 'Посмотреть всё портфолио →', filterAll: 'Все', filterVideos: 'Видео', filterShorts: 'Shorts', filterAnimations: '2D Motion', empty: 'В этой категории нет проектов.', pageTitle: 'Все Проекты' },
    about: { title: 'Обо мне', p1: 'Я Яцек. Уже 6 лет я занимаюсь видеомонтажом для авторов разного уровня.', p2: 'В работе я использую Premiere Pro и After Effects. Помимо видео, увлекаюсь программированием и спортом. Совмещаю работу и учебу в школе.' },
    qa: { label: 'FAQ', title: 'Вопросы и Ответы', subtitle: 'Частые вопросы о процессе и сроках.', q1: 'Каковы сроки выполнения?', a1: 'Обычно 3-5 рабочих дней.', q2: 'Какие программы вы используете?', a2: 'Premiere Pro, After Effects и DaVinci Resolve.', q3: 'Как проходит процесс сотрудничества?', a3: 'Консультация, передача материала и правки.', q4: 'Включено ли музыкальное сопровождение?', a4: 'Да, музыка без авторских прав включена.', q5: 'Как работают правки?', a5: 'Неограниченные правки до 100% результата.' },
    contact: { status: 'Свободен', title1: 'Начнем', title2: 'Монтаж.', subtitle: 'Есть исходники? Скопируйте email и обсудим детали!', btnCopy: 'Скопировать E-mail', btnCopied: 'Скопировано!' },
    footer: { home: 'Главная', portfolio: 'Портфолио', about: 'Обо мне', faq: 'FAQ', tttTitle: 'Хочешь сыграть?', tttWin: 'Вы выиграли!', tttLose: 'Вы проиграли!', tttDraw: 'Ничья!', tttPlayAgain: 'Сыграть еще' }
  },
  ja: {
    nav: { start: 'ホーム', portfolio: 'ポートフォリオ' },
    hero: { badge: 'ビデオエディター', subtitle1: 'あなたのビジョン', subtitle2: '私のプロダクション', subtitle3: 'リズム', subtitle4: 'フロー', subtitle5: 'ストーリー', btnStart: 'プロジェクト開始', btnPortfolio: 'ポートフォリオを見る', stat1: 'レビュー', stat2: '満足したクリエイター', stat3: '編集した動画', scroll: 'スクロール' },
    carousel: { title: '信頼されている' },
    portfolio: { label: 'ポートフォリオ', title: '厳選された<br />作品', subtitle: 'ポートフォリオからの最高のプロジェクト。', btnAll: '全ポートフォリオを見る →', filterAll: 'すべて', filterVideos: '動画', filterShorts: 'ショート', filterAnimations: '2D Motion', empty: 'このカテゴリーにはプロジェクトがありません。', pageTitle: '全プロジェクト' },
    about: { title: '私について', p1: '私はヤツェクです。6年間、さまざまなクリエイターのために動画編集を行ってきました。', p2: '日常の作業では、主にPremiere ProとAfter Effectsを使用しています。動画コンテンツへの情熱に加えて、プログラミングやスポーツにも興味があります。現在、高校での勉強とフリーランスの仕事を両立しています。' },
    qa: { label: 'FAQ', title: 'よくある質問', subtitle: 'ワークフロー、ツール、納期に関する質問。', q1: '納期はどのくらいですか？', a1: '通常は3〜5営業日です。', q2: 'どのソフトウェアを使用していますか？', a2: 'Premiere Pro、After Effects、DaVinci Resolveです。', q3: 'コラボレーションのプロセスは？', a3: '相談から始まり、フッテージを送信していただきます。', q4: '音楽は含まれますか？', a4: 'はい、著作権フリーの音楽が含まれます。', q5: '修正はどのように機能しますか？', a5: '100％満足するまで無制限に修正します。' },
    contact: { status: '対応可能', title1: '編集を', title2: '始めましょう。', subtitle: '素材がありますか？メールアドレスをコピーして詳細を話し合いましょう！', btnCopy: 'メールをコピー', btnCopied: 'コピーしました！' },
    footer: { home: 'ホーム', portfolio: 'ポートフォリオ', about: '私について', faq: 'FAQ', tttTitle: '勝負する？', tttWin: '勝ち！', tttLose: '負け！', tttDraw: '引き分け！', tttPlayAgain: 'もう一度プレイ' }
  }
};
